import ViaLeanTest.Smoke
import ViaLeanTest.Structural
import ViaLeanTest.Equality
import ViaLeanTest.Cut
import ViaLeanTest.Witness
import ViaLeanTest.UCB
import ViaLeanTest.Soundness
import ViaLeanTest.Iff
import ViaLeanTest.Model
